export const data = [
	{
		id: 1,
		img:'src/imagenes/Camisetaazul.jpg',
		nameProduct: 'Camiseta Azul',
		price: 55.000,
		quantity: 1,
	},
	{
		id: 2,
        img:'src/imagenes/Camisetablanca.webp',
		nameProduct: 'Camiseta Blanca',
		price: 55.000,
		quantity: 1,
	},
	{
		id: 3,
		img:'src/imagenes/Camisetagris.jpg',
		nameProduct: 'Camiseta Gris',
		price: 55.000,
		quantity: 1,
	},
	{
		id: 4,
		img:'src/imagenes/Camisetaverde.png',
		nameProduct: 'Camiseta Verde',
		price: 55.000,
		quantity: 1,
	},
	{
		id: 5,
		img:'src/imagenes/gorrablanca.jpeg',
		nameProduct: 'Gorra Blanca con Café',
		price: 40.000,
		quantity: 1,
	},
	{
		id: 6,
		img:'src/imagenes/gorramorada.jpeg',
		nameProduct: 'Gorra Blanca con Morado',
		price: 45.000,
		quantity: 1,
	},
    {
		id: 7,
		img:'src/imagenes/gorranegra.jpeg',
		nameProduct: 'Gorra Negra',
		price: 25.000,
		quantity: 1,
	},
    {
		id: 8,
		img:'src/imagenes/gorrarosa.jpeg',
		nameProduct: 'Gorra Rosada',
		price: 45.000,
		quantity: 1,
	},
    {
		id: 9,
		img:'src/imagenes/pantalon1.webp',
		nameProduct: 'Pantalón Negro para Hombre',
		price: 115.000,
		quantity: 1,
	},
    {
		id: 10,
		img:'src/imagenes/pantalon2.webp',
		nameProduct: 'Pantalón Negro para Dama',
		price: 90.000,
		quantity: 1,
	},
    {
		id: 11,
		img:'src/imagenes/pantalon3.png',
		nameProduct: 'Pantalón Café para Hombre',
		price: 110.000,
		quantity: 1,
	},
	{
		id: 12,
		img:'src/imagenes/3.png',
		nameProduct: 'Chaqueta mujer',
		price: 140.000,
		quantity: 1,
	},
];